// <auto-generated />
namespace UFC_Rankings.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class addinglastnametoranking : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addinglastnametoranking));
        
        string IMigrationMetadata.Id
        {
            get { return "202002110809403_adding-last-name-to-ranking"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
